name: daterange
description: Encapsulates a start and end DateTime that represent the range of dates.
version: 1.0.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/dart_date_range
issue_tracker: https://github.com/Innim/dart_date_range/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
